//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBTRACK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int TaskId { get; set; }
        public int OwnerId { get; set; }
        public bool status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime StatusChangedOn { get; set; }
    }
}
